# Generated by Django 2.2.6 on 2020-07-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200718_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='count',
            new_name='popularity',
        ),
    ]
