# Generated by Django 2.2.6 on 2020-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200718_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='display_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
